apiVersion: v1
kind: ConfigMap
metadata:
  name: kubestronaut-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="zh-TW">
    <head>
      <meta charset="UTF-8">
      <title>Kubestronaut</title>
    </head>
    <body>
      <h1>👨‍🚀 Kubestronaut 網頁</h1>
      <img src="data:image/png;base64,{{IMAGE_BASE64}}" width="300" />
      <p id="time"></p>
      <p id="timezone"></p>
      <script>
        const now = new Date();
        document.getElementById('time').textContent = `現在時間：${now.toLocaleString()}`;
        document.getElementById('timezone').textContent = `時區：${Intl.DateTimeFormat().resolvedOptions().timeZone}`;
      </script>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestronaut-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubestronaut-nginx
  template:
    metadata:
      labels:
        app: kubestronaut-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: kubestronaut-html
---
apiVersion: v1
kind: Service
metadata:
  name: kubestronaut-nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: kubestronaut-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036

